const regionNames = new Intl.DisplayNames(["en"], {
  type: "region",
})

// GDELT Geo country codes use FIPS 10-4 codes, not ISO 3166-1 alpha-2.
// Map GDELT/FIPS -> ISO alpha-2 before using Intl.DisplayNames or COUNTRY_NAMES.
const GDELT_TO_ISO: Record<string, string> = {
  AF: "AF",
  AL: "AL",
  AG: "DZ",
  AQ: "AS",
  AN: "AD",
  AO: "AO",
  AV: "AI",
  AC: "AG",
  AR: "AR",
  AM: "AM",
  AA: "AW",
  AS: "AU",
  AU: "AT",
  AJ: "AZ",

  BF: "BS",
  BA: "BH",
  BG: "BD",
  BB: "BB",
  BS: "BY",
  BE: "BE",
  BH: "BZ",
  BN: "BJ",
  BD: "BM",
  BT: "BT",
  BL: "BO",
  BK: "BA",
  BC: "BW",
  BR: "BR",
  BX: "BN",
  BU: "BG",
  UV: "BF",
  BM: "MM",
  BY: "BI",

  CB: "KH",
  CM: "CM",
  CA: "CA",
  CV: "CV",
  CJ: "KY",
  CT: "CF",
  CD: "TD",
  CI: "CL",
  CH: "CN",
  KT: "CX",
  CK: "CC",
  CO: "CO",
  CN: "KM",
  CF: "CG",
  CG: "CD",
  CS: "CR",
  IV: "CI",
  HR: "HR",
  CU: "CU",
  CY: "CY",
  EZ: "CZ",

  DA: "DK",
  DJ: "DJ",
  DO: "DM",
  DR: "DO",

  EC: "EC",
  EG: "EG",
  ES: "SV",
  EK: "GQ",
  ER: "ER",
  EN: "EE",
  ET: "ET",

  FK: "FK",
  FO: "FO",
  FJ: "FJ",
  FI: "FI",
  FR: "FR",
  FG: "GF",
  FP: "PF",
  FS: "TF",

  GB: "GA",
  GA: "GM",
  GG: "GE",
  GM: "DE",
  GH: "GH",
  GR: "GR",
  GL: "GL",
  GJ: "GD",
  GP: "GP",
  GQ: "GU",
  GT: "GT",
  GY: "GY",

  HA: "HT",
  HO: "HN",
  HK: "HK",
  HU: "HU",

  IC: "IS",
  IN: "IN",
  ID: "ID",
  IR: "IR",
  IZ: "IQ",
  EI: "IE",
  IS: "IL",
  IT: "IT",

  JM: "JM",
  JA: "JP",
  JE: "JE",
  JO: "JO",

  KZ: "KZ",
  KE: "KE",
  KR: "KI",
  KN: "KP",
  KS: "KR",
  KU: "KW",
  KG: "KG",

  LA: "LA",
  LG: "LV",
  LE: "LB",
  LT: "LS",
  LI: "LR",
  LY: "LY",
  LS: "LI",
  LH: "LT",
  LU: "LU",

  MC: "MO",
  MA: "MG",
  MI: "MW",
  MY: "MY",
  MV: "MV",
  ML: "ML",
  MT: "MT",
  RM: "MH",
  MR: "MQ",
  MP: "MU",
  MF: "YT",
  MX: "MX",
  FM: "FM",
  MD: "MD",
  MN: "MC",
  MG: "MN",
  MJ: "ME",
  MH: "MS",
  MO: "MA",
  MZ: "MZ",

  WA: "NA",
  NR: "NR",
  NP: "NP",
  NL: "NL",
  NC: "NC",
  NZ: "NZ",
  NU: "NI",
  NG: "NE",
  NI: "NG",
  NN: "NU",
  NO: "NO",

  MU: "OM",

  PK: "PK",
  PS: "PW",
  PA: "PA",
  PP: "PG",
  PE: "PE",
  RP: "PH",
  PC: "PN",
  PL: "PL",
  PO: "PT",
  RQ: "PR",

  QA: "QA",
  RE: "RE",
  RO: "RO",
  RS: "RU",
  RW: "RW",

  SM: "SM",
  TP: "ST",
  SA: "SA",
  SG: "SN",
  RB: "RS",
  SE: "SC",
  SL: "SL",
  SN: "SG",
  LO: "SK",
  SI: "SI",
  BP: "SB",
  SO: "SO",
  SF: "ZA",
  SP: "ES",
  CE: "LK",
  SU: "SD",
  NS: "SR",
  WZ: "SZ",
  SW: "SE",
  SZ: "CH",
  SY: "SY",

  TW: "TW",
  TI: "TJ",
  TZ: "TZ",
  TH: "TH",
  TO: "TG",
  TL: "TK",
  TN: "TO",
  TD: "TT",
  TS: "TN",
  TU: "TR",
  TX: "TM",
  TK: "TC",
  TV: "TV",

  UG: "UG",
  UP: "UA",
  AE: "AE",
  UK: "GB",
  US: "US",
  UY: "UY",
  UZ: "UZ",

  NH: "VU",
  VE: "VE",
  VM: "VN",
  VQ: "VI",

  WF: "WF",
  WE: "EH",
  YM: "YE",
  ZA: "ZM",
  ZI: "ZW",
}

// ISO 3166-1 alpha-2 
export const COUNTRY_NAMES: Record<string, string> = {
  "AF": "Afghanistan",
  "AX": "Åland Islands",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua & Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BQ": "Caribbean Netherlands",
  "BA": "Bosnia & Herzegovina",
  "BW": "Botswana",
  "BV": "Bouvet Island",
  "BR": "Brazil",
  "IO": "British Indian Ocean Territory",
  "BN": "Brunei",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "CV": "Cape Verde",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CX": "Christmas Island",
  "CC": "Cocos (Keeling) Islands",
  "CO": "Colombia",
  "KM": "Comoros",
  "CG": "Congo - Brazzaville",
  "CD": "Congo - Kinshasa",
  "CK": "Cook Islands",
  "CR": "Costa Rica",
  "CI": "Côte d’Ivoire",
  "HR": "Croatia",
  "CU": "Cuba",
  "CW": "Curaçao",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "SZ": "Eswatini",
  "ET": "Ethiopia",
  "FK": "Falkland Islands",
  "FO": "Faroe Islands",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GF": "French Guiana",
  "PF": "French Polynesia",
  "TF": "French Southern Territories",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard & McDonald Islands",
  "VA": "Vatican City",
  "HN": "Honduras",
  "HK": "Hong Kong SAR China",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IM": "Isle of Man",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JE": "Jersey",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "North Korea",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Laos",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macao SAR China",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesia",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar (Burma)",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "NC": "New Caledonia",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk Island",
  "MK": "North Macedonia",
  "MP": "Northern Mariana Islands",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestinian Territories",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PN": "Pitcairn Islands",
  "PL": "Poland",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RU": "Russia",
  "RW": "Rwanda",
  "BL": "St. Barthélemy",
  "SH": "St. Helena",
  "KN": "St. Kitts & Nevis",
  "LC": "St. Lucia",
  "MF": "St. Martin",
  "PM": "St. Pierre & Miquelon",
  "VC": "St. Vincent & Grenadines",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "São Tomé & Príncipe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SX": "Sint Maarten",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "GS": "South Georgia & South Sandwich Islands",
  "SS": "South Sudan",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SJ": "Svalbard & Jan Mayen",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syria",
  "TW": "Taiwan",
  "TJ": "Tajikistan",
  "TZ": "Tanzania",
  "TH": "Thailand",
  "TL": "Timor-Leste",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad & Tobago",
  "TN": "Tunisia",
  "TR": "Türkiye",
  "TM": "Turkmenistan",
  "TC": "Turks & Caicos Islands",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom",
  "US": "United States",
  "UM": "U.S. Outlying Islands",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "VG": "British Virgin Islands",
  "VI": "U.S. Virgin Islands",
  "WF": "Wallis & Futuna",
  "EH": "Western Sahara",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
};

/**
 * Convert a GDELT/FIPS country code to ISO.
 *
 * Examples:
 *   SF -> ZA
 *   RP -> PH
 *   IN -> IN
 */
export function gdeltToIso(
  code: string | null | undefined
): string | null {
  if (!code) return null

  const upper = code.toUpperCase()

  return GDELT_TO_ISO[upper] ?? upper
}

/**
 * Convert an ISO country code to the GDELT/FIPS code
 * used by GDELT Geo fields.
 *
 * Examples:
 *   ZA -> SF
 *   PH -> RP
 *   IN -> IN
 */
export function isoToGdelt(
  code: string | null | undefined
): string | null {
  if (!code) return null

  const upper = code.toUpperCase()

  if (upper === "ALL") return "all"

  // Build the reverse lookup from GDELT_TO_ISO.
  const entry = Object.entries(GDELT_TO_ISO).find(
    ([, iso]) => iso === upper
  )

  return entry?.[0] ?? upper
}

/**
 * Get a country name from either an ISO or GDELT/FIPS code.
 *
 * Examples:
 *   ZA -> South Africa
 *   SF -> South Africa
 *   PH -> Philippines
 *   RP -> Philippines
 */
export function getCountryName(
  code: string | null | undefined
): string {
  if (!code) return "Unknown"

  const isoCode = gdeltToIso(code)

  if (!isoCode) return "Unknown"

  if (COUNTRY_NAMES[isoCode]) {
    return COUNTRY_NAMES[isoCode]
  }

  try {
    return regionNames.of(isoCode) ?? isoCode
  } catch {
    return isoCode
  }
}
